M48
; DRILL file {KiCad 9.0.1} date 2025-05-15T13:05:12+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-15T13:05:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X160.53Y-44.78
X160.53Y-145.78
X224.53Y-44.78
X224.53Y-145.78
M30
