M48
; DRILL file {KiCad 9.0.0} date 2025-04-21T14:10:10+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-21T14:10:10+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X6.3201Y-1.763
X6.3201Y-5.7394
X8.8398Y-1.763
X8.8398Y-5.7394
M30
