M48
; DRILL file {KiCad 9.0.0} date 2025-04-21T16:10:47+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-21T16:10:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.6063Y-2.0177
X4.6063Y-5.9744
X7.1063Y-2.0177
X7.1063Y-5.9744
M30
